### ISSUE TITLE
Getting `light` mode even though iOS is set to dark

### ISSUE THREAD

**Issue by yolpsoftware** [codemotionapps/react-native-dynamic#12]
See comment below..

~~`react-native-dark-mode` has had the `DarkModeProvider` and `DarkModeContext`, which could be used from class components, as described here: https://stackoverflow.com/questions/60486572/how-to-implement-react-native-dark-mode-in-ios~~

~~In `react-native-dynamic`, I can't find anything for class components. Everything seems to be working over hooks. Of course, hooks are the future, but there are components that have not yet been "migrated" to hooks.~~

~~Can RNdynamic be used with class components?~~

**Comment by yolpsoftware** [comment]
Sorry, my TypeScript somehow didn't show the classes. They are still there.

However, on my iPhone, `this.context` is set to `light`, even though I have activated the iOS dark mode. Any idea?

**Comment by dimitarnestorov** [comment]
Try disabling debugger

**Comment by yolpsoftware** [comment]
Uh, okay. Why?

**Comment by dimitarnestorov** [comment]
It’s a React Native limitation. Does it work?

**Comment by yolpsoftware** [comment]
Yes, as I said, it works. Thx for the hint.

Is that limitation documented somewhere? Just curious.

**Comment by dimitarnestorov** [comment]
https://reactnative.dev/docs/appearance
![CC11C762-6C5B-49AD-BC9F-A301CF051BFD](https://user-images.githubusercontent.com/8790386/92334793-c55b9f00-f099-11ea-9a85-4d33196da381.jpeg)

**Comment by yolpsoftware** [comment]
I see. You should mention that in your readme.

Also, a setting to force dark mode while debugging would be handy.
