### ISSUE TITLE
How to use useDarkMode in react-navigation?

### ISSUE THREAD

**Issue by me1k** [codemotionapps/react-native-dynamic#14]
For example i have 

const HomeTabNavigator = createBottomTabNavigator(
  {
    Home: {
      screen: HomeScreen,
      path: '',
      navigationOptions: {
        tabBarIcon: ({ tintColor }) => (
          <Icon name="home" size={30} color={tintColor} />
        ),
      },
    },
  {
    swipeEnabled: true,
    animationEnabled: true,
    navigationOptions: ({ navigation }) => ({
      header: null,
    }),
    tabBarOptions: {
      showLabel: true,
      activeTintColor: '#fff',
      inactiveTintColor: 'lightgrey',
      style: { backgroundColor: darkMode ? 'black' : '#0080FF' },
      labelStyle: { fontSize: 12 },
      tabStyle: { height: 65 },
    },
  }
)

how can i use `useDarkMode` within the createTabNavigator ? Because it says that i cannot use hooks here

**Comment by dimitarnestorov** [comment]
https://reactnavigation.org/docs/themes

**Comment by meikbolender** [comment]
> https://reactnavigation.org/docs/themes

Thank you, but this is for Version 5.

I dont see a posibility of theming for Version 4 in the Docs?

**Comment by dimitarnestorov** [comment]
In version 4 you can use `screenProps`. Pass a custom `darkMode` screen prop in your `App` component and then use a function.
```js
{
	tabBarOptions: ({ tintColor }) => ({
	    // ..
        style: { backgroundColor: darkMode ? 'black' : '#0080FF' },
        // ..
	})
}
```

**Comment by meikbolender** [comment]
> In version 4 you can use `screenProps`. Pass a custom `darkMode` screen prop in your `App` component and then use a function.
> 
> ```js
> {
> 	tabBarOptions: ({ screenProps }) => ({
> 	    // ..
>         style: { backgroundColor: screenProps.darkMode ? 'black' : '#0080FF' },
>         // ..
> 	}),
> }
> ```

Thank you very much! And of course V4 supports Theming, my bad. sorry
I will try your proposal this evening
