### ISSUE TITLE
Component Exception

### ISSUE THREAD

**Issue by jacow** [codemotionapps/react-native-dynamic#17]
![Simulator Screen Shot - iPhone 11 - 2020-10-10 at 22 28 49](https://user-images.githubusercontent.com/1515728/95658919-0c7cfa00-0b48-11eb-8eae-1c834eb272df.png)

May you help me why i always got this log ?
I used useDynamicValue like this :

class Root extends Component {
  render () {
    const color = useDynamicValue('black', 'white')
      return (

**Comment by DimitarNestorov** [comment]
See https://github.com/codemotionapps/react-native-dark-mode/issues/27#issuecomment-559917799
