### ISSUE TITLE
useDarkMode() always returning false on simulator

### ISSUE THREAD

**Issue by patrick-tresp** [codemotionapps/react-native-dynamic#9]
Hi,

just implemented this library, and using 

```const isDarkMode = useDarkMode()```

within a component leads always to return `false` on ( iOS ) simulator.

I enabled dark mode via: settings-> developer -> Appearance -> Dark Mode

Does it work on simulator or devices only?

Thanks!

**Comment by dimitarnestorov** [comment]
Try disabling debugger

**Comment by patrick-tresp** [comment]
perfect, that works! unfortunately, i need to use Alert to check for some behaviours then.

Cheers, thanks for superfast reply!
